<?php

// @codingStandardsIgnoreFile

/**  @var $block \Vekeryk\SaveCart\Block\Cart */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<div class="box">
    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Shipping Cart Information') ?></span></strong>
    <div class="box-content">
        <div><?php echo $block->escapeHtml(__('Cart Name / Job Name / PO Number')); ?>: <?php echo $block->escapeHtml($block->getQuoteName()) ?></div>
        <div><?php /* @escapeNotVerified */ echo __('Note') ?>: <?php echo $block->escapeHtml($block->getQuoteComment()) ?></div>
    </div>
</div>
<div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
    <table id="shopping-cart-table"
           class="cart items data table"
           data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
           "updateCartActionContainer": "#update_cart_action_container"}}'>
        <caption role="heading" aria-level="2" class="table-caption"><?php /* @escapeNotVerified */ echo __('Shopping Cart Items') ?></caption>
        <thead>
            <tr>
                <th class="col item" scope="col"><span><?php /* @escapeNotVerified */ echo __('Item') ?></span></th>
                <th class="col price" scope="col"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></th>
                <th class="col qty" scope="col"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></th>
                <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
            </tr>
        </thead>
        <?php foreach ($block->getItems() as $_item): ?>
            <?php echo $block->getItemHtml($_item) ?>
        <?php endforeach ?>
        <tfoot>
            <?php echo $block->getTotals(); ?>
        </tfoot>
    </table>
</div>

<?php //echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>

